-- Liderlik Aynası — temel şema
create extension if not exists pgcrypto;

create table public.participants (
  id          uuid primary key default gen_random_uuid(),
  full_name   text not null,
  team        text,
  city        text,
  phone       text,
  login_code  char(6) not null unique check (login_code ~ '^[0-9]{6}$'),
  role        text not null default 'participant' check (role in ('participant','admin')),
  created_at  timestamptz not null default now()
);

create table public.traits (
  id               smallint generated by default as identity primary key,
  name             text not null,
  observation_hint text not null,
  sort_order       smallint not null,
  active           boolean not null default true
);

create table public.waves (
  id        smallint primary key check (id in (1,2,3)),
  name      text not null,
  is_open   boolean not null default false,
  opened_at timestamptz,
  closed_at timestamptz
);

create table public.assignments (
  id          uuid primary key default gen_random_uuid(),
  observer_id uuid not null references public.participants(id) on delete cascade,
  target_id   uuid not null references public.participants(id) on delete cascade,
  type        text not null check (type in ('shadow','open')),
  created_at  timestamptz not null default now(),
  constraint assignments_no_self check (observer_id <> target_id),
  constraint assignments_unique unique (observer_id, target_id, type)
);

create table public.ratings (
  id         uuid primary key default gen_random_uuid(),
  rater_id   uuid not null references public.participants(id) on delete cascade,
  target_id  uuid not null references public.participants(id) on delete cascade,
  trait_id   smallint not null references public.traits(id),
  wave       smallint not null references public.waves(id),
  score      smallint not null check (score between 1 and 10),
  comment    text,
  is_self    boolean generated always as (rater_id = target_id) stored,
  is_hidden  boolean not null default false,
  created_at timestamptz not null default now(),
  constraint ratings_once_per_wave unique (rater_id, target_id, trait_id, wave)
);

create table public.settings (
  key        text primary key,
  value      text not null,
  updated_at timestamptz not null default now()
);

create table public.login_attempts (
  id         bigint generated always as identity primary key,
  ip         text not null,
  success    boolean not null,
  created_at timestamptz not null default now()
);

-- Ağır okuma desenleri: rapor agregatları (hedef+dalga), "verdiğim puanlar", ekran agregatları
create index idx_ratings_target_wave  on public.ratings (target_id, wave);
create index idx_ratings_rater_wave   on public.ratings (rater_id, wave);
create index idx_ratings_wave_trait   on public.ratings (wave, trait_id);
create index idx_assignments_observer on public.assignments (observer_id);
create index idx_assignments_target   on public.assignments (target_id);
create index idx_login_attempts_ip_time on public.login_attempts (ip, created_at);
